# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from Car_Spraying/SetTwoAngle.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class SetTwoAngle(genpy.Message):
  _md5sum = "f1d10f92f012da8da765573aa414a014"
  _type = "Car_Spraying/SetTwoAngle"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """uint8 id0
float32 angle0
uint8 id1
float32 angle1"""
  __slots__ = ['id0','angle0','id1','angle1']
  _slot_types = ['uint8','float32','uint8','float32']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       id0,angle0,id1,angle1

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(SetTwoAngle, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.id0 is None:
        self.id0 = 0
      if self.angle0 is None:
        self.angle0 = 0.
      if self.id1 is None:
        self.id1 = 0
      if self.angle1 is None:
        self.angle1 = 0.
    else:
      self.id0 = 0
      self.angle0 = 0.
      self.id1 = 0
      self.angle1 = 0.

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_BfBf().pack(_x.id0, _x.angle0, _x.id1, _x.angle1))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 10
      (_x.id0, _x.angle0, _x.id1, _x.angle1,) = _get_struct_BfBf().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_BfBf().pack(_x.id0, _x.angle0, _x.id1, _x.angle1))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 10
      (_x.id0, _x.angle0, _x.id1, _x.angle1,) = _get_struct_BfBf().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_BfBf = None
def _get_struct_BfBf():
    global _struct_BfBf
    if _struct_BfBf is None:
        _struct_BfBf = struct.Struct("<BfBf")
    return _struct_BfBf
