obstacle_range: 2.5
raytrace_range: 3.0
robot_radius: 0.3
inflation_radius: 0.1
max_obstacle_height: 0.6
min_obstacle_height: 0.0
# observation_sources: scan
# scan: {data_type: LaserScan, topic: /scan, marking: true, clearing: true, expected_update_rate: 0}

obstacles:
  observation_sources: scan
  scan: {data_type: LaserScan, topic: /scan, marking: true, clearing: true, expected_update_rate: 0}
 
depth_layer:
  observation_sources: scan
  scan: {data_type: LaserScan, topic: /pcl_scan, marking: true, clearing: true, expected_update_rate: 0}
