// Generated by gencpp from file Car_Spraying/QueryServoAngle.msg
// DO NOT EDIT!


#ifndef CAR_SPRAYING_MESSAGE_QUERYSERVOANGLE_H
#define CAR_SPRAYING_MESSAGE_QUERYSERVOANGLE_H

#include <ros/service_traits.h>


#include <Car_Spraying/QueryServoAngleRequest.h>
#include <Car_Spraying/QueryServoAngleResponse.h>


namespace Car_Spraying
{

struct QueryServoAngle
{

typedef QueryServoAngleRequest Request;
typedef QueryServoAngleResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct QueryServoAngle
} // namespace Car_Spraying


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::Car_Spraying::QueryServoAngle > {
  static const char* value()
  {
    return "3fa0610a2c670f4fbf342f6899c09e8c";
  }

  static const char* value(const ::Car_Spraying::QueryServoAngle&) { return value(); }
};

template<>
struct DataType< ::Car_Spraying::QueryServoAngle > {
  static const char* value()
  {
    return "Car_Spraying/QueryServoAngle";
  }

  static const char* value(const ::Car_Spraying::QueryServoAngle&) { return value(); }
};


// service_traits::MD5Sum< ::Car_Spraying::QueryServoAngleRequest> should match
// service_traits::MD5Sum< ::Car_Spraying::QueryServoAngle >
template<>
struct MD5Sum< ::Car_Spraying::QueryServoAngleRequest>
{
  static const char* value()
  {
    return MD5Sum< ::Car_Spraying::QueryServoAngle >::value();
  }
  static const char* value(const ::Car_Spraying::QueryServoAngleRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::Car_Spraying::QueryServoAngleRequest> should match
// service_traits::DataType< ::Car_Spraying::QueryServoAngle >
template<>
struct DataType< ::Car_Spraying::QueryServoAngleRequest>
{
  static const char* value()
  {
    return DataType< ::Car_Spraying::QueryServoAngle >::value();
  }
  static const char* value(const ::Car_Spraying::QueryServoAngleRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::Car_Spraying::QueryServoAngleResponse> should match
// service_traits::MD5Sum< ::Car_Spraying::QueryServoAngle >
template<>
struct MD5Sum< ::Car_Spraying::QueryServoAngleResponse>
{
  static const char* value()
  {
    return MD5Sum< ::Car_Spraying::QueryServoAngle >::value();
  }
  static const char* value(const ::Car_Spraying::QueryServoAngleResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::Car_Spraying::QueryServoAngleResponse> should match
// service_traits::DataType< ::Car_Spraying::QueryServoAngle >
template<>
struct DataType< ::Car_Spraying::QueryServoAngleResponse>
{
  static const char* value()
  {
    return DataType< ::Car_Spraying::QueryServoAngle >::value();
  }
  static const char* value(const ::Car_Spraying::QueryServoAngleResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // CAR_SPRAYING_MESSAGE_QUERYSERVOANGLE_H
