// Generated by gencpp from file Car_Spraying/SetServoAngle.msg
// DO NOT EDIT!


#ifndef CAR_SPRAYING_MESSAGE_SETSERVOANGLE_H
#define CAR_SPRAYING_MESSAGE_SETSERVOANGLE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace Car_Spraying
{
template <class ContainerAllocator>
struct SetServoAngle_
{
  typedef SetServoAngle_<ContainerAllocator> Type;

  SetServoAngle_()
    : id(0)
    , angle(0.0)  {
    }
  SetServoAngle_(const ContainerAllocator& _alloc)
    : id(0)
    , angle(0.0)  {
  (void)_alloc;
    }



   typedef uint8_t _id_type;
  _id_type id;

   typedef float _angle_type;
  _angle_type angle;





  typedef boost::shared_ptr< ::Car_Spraying::SetServoAngle_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::Car_Spraying::SetServoAngle_<ContainerAllocator> const> ConstPtr;

}; // struct SetServoAngle_

typedef ::Car_Spraying::SetServoAngle_<std::allocator<void> > SetServoAngle;

typedef boost::shared_ptr< ::Car_Spraying::SetServoAngle > SetServoAnglePtr;
typedef boost::shared_ptr< ::Car_Spraying::SetServoAngle const> SetServoAngleConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::Car_Spraying::SetServoAngle_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::Car_Spraying::SetServoAngle_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::Car_Spraying::SetServoAngle_<ContainerAllocator1> & lhs, const ::Car_Spraying::SetServoAngle_<ContainerAllocator2> & rhs)
{
  return lhs.id == rhs.id &&
    lhs.angle == rhs.angle;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::Car_Spraying::SetServoAngle_<ContainerAllocator1> & lhs, const ::Car_Spraying::SetServoAngle_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace Car_Spraying

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::Car_Spraying::SetServoAngle_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::Car_Spraying::SetServoAngle_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::Car_Spraying::SetServoAngle_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::Car_Spraying::SetServoAngle_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::Car_Spraying::SetServoAngle_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::Car_Spraying::SetServoAngle_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::Car_Spraying::SetServoAngle_<ContainerAllocator> >
{
  static const char* value()
  {
    return "39fc2bc02ee4598568e833e115b496ba";
  }

  static const char* value(const ::Car_Spraying::SetServoAngle_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x39fc2bc02ee45985ULL;
  static const uint64_t static_value2 = 0x68e833e115b496baULL;
};

template<class ContainerAllocator>
struct DataType< ::Car_Spraying::SetServoAngle_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Car_Spraying/SetServoAngle";
  }

  static const char* value(const ::Car_Spraying::SetServoAngle_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::Car_Spraying::SetServoAngle_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint8 id\n"
"float32 angle\n"
;
  }

  static const char* value(const ::Car_Spraying::SetServoAngle_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::Car_Spraying::SetServoAngle_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.id);
      stream.next(m.angle);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SetServoAngle_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::Car_Spraying::SetServoAngle_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::Car_Spraying::SetServoAngle_<ContainerAllocator>& v)
  {
    s << indent << "id: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.id);
    s << indent << "angle: ";
    Printer<float>::stream(s, indent + "  ", v.angle);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CAR_SPRAYING_MESSAGE_SETSERVOANGLE_H
