// Generated by gencpp from file Car_Spraying/SetTwoAngle.msg
// DO NOT EDIT!


#ifndef CAR_SPRAYING_MESSAGE_SETTWOANGLE_H
#define CAR_SPRAYING_MESSAGE_SETTWOANGLE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace Car_Spraying
{
template <class ContainerAllocator>
struct SetTwoAngle_
{
  typedef SetTwoAngle_<ContainerAllocator> Type;

  SetTwoAngle_()
    : id0(0)
    , angle0(0.0)
    , id1(0)
    , angle1(0.0)  {
    }
  SetTwoAngle_(const ContainerAllocator& _alloc)
    : id0(0)
    , angle0(0.0)
    , id1(0)
    , angle1(0.0)  {
  (void)_alloc;
    }



   typedef uint8_t _id0_type;
  _id0_type id0;

   typedef float _angle0_type;
  _angle0_type angle0;

   typedef uint8_t _id1_type;
  _id1_type id1;

   typedef float _angle1_type;
  _angle1_type angle1;





  typedef boost::shared_ptr< ::Car_Spraying::SetTwoAngle_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::Car_Spraying::SetTwoAngle_<ContainerAllocator> const> ConstPtr;

}; // struct SetTwoAngle_

typedef ::Car_Spraying::SetTwoAngle_<std::allocator<void> > SetTwoAngle;

typedef boost::shared_ptr< ::Car_Spraying::SetTwoAngle > SetTwoAnglePtr;
typedef boost::shared_ptr< ::Car_Spraying::SetTwoAngle const> SetTwoAngleConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::Car_Spraying::SetTwoAngle_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::Car_Spraying::SetTwoAngle_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::Car_Spraying::SetTwoAngle_<ContainerAllocator1> & lhs, const ::Car_Spraying::SetTwoAngle_<ContainerAllocator2> & rhs)
{
  return lhs.id0 == rhs.id0 &&
    lhs.angle0 == rhs.angle0 &&
    lhs.id1 == rhs.id1 &&
    lhs.angle1 == rhs.angle1;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::Car_Spraying::SetTwoAngle_<ContainerAllocator1> & lhs, const ::Car_Spraying::SetTwoAngle_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace Car_Spraying

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::Car_Spraying::SetTwoAngle_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::Car_Spraying::SetTwoAngle_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::Car_Spraying::SetTwoAngle_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::Car_Spraying::SetTwoAngle_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::Car_Spraying::SetTwoAngle_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::Car_Spraying::SetTwoAngle_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::Car_Spraying::SetTwoAngle_<ContainerAllocator> >
{
  static const char* value()
  {
    return "f1d10f92f012da8da765573aa414a014";
  }

  static const char* value(const ::Car_Spraying::SetTwoAngle_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xf1d10f92f012da8dULL;
  static const uint64_t static_value2 = 0xa765573aa414a014ULL;
};

template<class ContainerAllocator>
struct DataType< ::Car_Spraying::SetTwoAngle_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Car_Spraying/SetTwoAngle";
  }

  static const char* value(const ::Car_Spraying::SetTwoAngle_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::Car_Spraying::SetTwoAngle_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint8 id0\n"
"float32 angle0\n"
"uint8 id1\n"
"float32 angle1\n"
;
  }

  static const char* value(const ::Car_Spraying::SetTwoAngle_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::Car_Spraying::SetTwoAngle_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.id0);
      stream.next(m.angle0);
      stream.next(m.id1);
      stream.next(m.angle1);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SetTwoAngle_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::Car_Spraying::SetTwoAngle_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::Car_Spraying::SetTwoAngle_<ContainerAllocator>& v)
  {
    s << indent << "id0: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.id0);
    s << indent << "angle0: ";
    Printer<float>::stream(s, indent + "  ", v.angle0);
    s << indent << "id1: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.id1);
    s << indent << "angle1: ";
    Printer<float>::stream(s, indent + "  ", v.angle1);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CAR_SPRAYING_MESSAGE_SETTWOANGLE_H
